In [2]:
import mediapipe as mp
import cv2
import time
import pandas as pd

In [3]:
# Initialize MediaPipe Hands module
mp_hands = mp.solutions.hands
hands = mp_hands.Hands()

# Function to extract landmarks
def get_landmarks(image):
    landmark_list = []
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image_rgb)
    
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            for landmark in hand_landmarks.landmark:
                # Multiply x and y values by image width and height to get pixel values
                x = int(landmark.x * image.shape[1])
                y = int(landmark.y * image.shape[0])
                landmark_list.append((x, y))
    return landmark_list

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

In [10]:
landmarks = []
left = []
cap=cv2.VideoCapture(1)
# print(f"collecting images for {i}")
time.sleep(5)
j=0
while len(left)<250:
    print(f"image number : {j}")
    j+=1
    ret,frame =cap.read()
    cv2.imshow("frame",frame)
    if get_landmarks(frame):
        left.append(get_landmarks(frame))
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

image number : 0
image number : 1
image number : 2
image number : 3
image number : 4
image number : 5
image number : 6
image number : 7
image number : 8
image number : 9
image number : 10
image number : 11
image number : 12
image number : 13
image number : 14
image number : 15
image number : 16
image number : 17
image number : 18
image number : 19
image number : 20
image number : 21
image number : 22
image number : 23
image number : 24
image number : 25
image number : 26
image number : 27
image number : 28
image number : 29
image number : 30
image number : 31
image number : 32
image number : 33
image number : 34
image number : 35
image number : 36
image number : 37
image number : 38
image number : 39
image number : 40
image number : 41
image number : 42
image number : 43
image number : 44
image number : 45
image number : 46
image number : 47
image number : 48
image number : 49
image number : 50
image number : 51
image number : 52
image number : 53
image number : 54
image number : 55
image number : 56
image number : 57
image number : 58
image number : 59
image number : 60
image number : 61
image number : 62
image number : 63
image number : 64
image number : 65
image number : 66
image number : 67
image number : 68
image number : 69
image number : 70
image number : 71
image number : 72
image number : 73
image number : 74
image number : 75
image number : 76
image number : 77
image number : 78
image number : 79
image number : 80
image number : 81
image number : 82
image number : 83
image number : 84
image number : 85
image number : 86
image number : 87
image number : 88
image number : 89
image number : 90
image number : 91
image number : 92
image number : 93
image number : 94
image number : 95
image number : 96
image number : 97
image number : 98
image number : 99
image number : 100
image number : 101
image number : 102
image number : 103
image number : 104
image number : 105
image number : 106
image number : 107
image number : 108
image number : 109
image number : 110
image number : 111
image number : 112
image number : 113
image number : 114
image number : 115
image number : 116
image number : 117
image number : 118
image number : 119
image number : 120
image number : 121
image number : 122
image number : 123
image number : 124
image number : 125
image number : 126
image number : 127
image number : 128
image number : 129
image number : 130
image number : 131
image number : 132
image number : 133
image number : 134
image number : 135
image number : 136
image number : 137
image number : 138
image number : 139
image number : 140
image number : 141
image number : 142
image number : 143
image number : 144
image number : 145
image number : 146
image number : 147
image number : 148
image number : 149
image number : 150
image number : 151
image number : 152
image number : 153
image number : 154
image number : 155
image number : 156
image number : 157
image number : 158
image number : 159
image number : 160
image number : 161
image number : 162
image number : 163
image number : 164
image number : 165
image number : 166
image number : 167
image number : 168
image number : 169
image number : 170
image number : 171
image number : 172
image number : 173
image number : 174
image number : 175
image number : 176
image number : 177
image number : 178
image number : 179
image number : 180
image number : 181
image number : 182
image number : 183
image number : 184
image number : 185
image number : 186
image number : 187
image number : 188
image number : 189
image number : 190
image number : 191
image number : 192
image number : 193
image number : 194
image number : 195
image number : 196
image number : 197
image number : 198
image number : 199
image number : 200
image number : 201
image number : 202
image number : 203
image number : 204
image number : 205
image number : 206
image number : 207
image number : 208
image number : 209
image number : 210
image number : 211
image number : 212
image number : 213
image number : 214
image number : 215
image number : 216
image number : 217
image number : 218
image number : 219
image number : 220
image number : 221
image number : 222
image number : 223
image number : 224
image number : 225
image number : 226
image number : 227
image number : 228
image number : 229
image number : 230
image number : 231
image number : 232
image number : 233
image number : 234
image number : 235
image number : 236
image number : 237
image number : 238
image number : 239
image number : 240
image number : 241
image number : 242
image number : 243
image number : 244
image number : 245
image number : 246
image number : 247
image number : 248
image number : 249
image number : 250
image number : 251
image number : 252
image number : 253
image number : 254
image number : 255
image number : 256
image number : 257
image number : 258
image number : 259
image number : 260
image number : 261
image number : 262
image number : 263
image number : 264
image number : 265
image number : 266

In [49]:
len(left)
# left

50

In [11]:
lis=[]
for i in left:
    lis1=[]
    for j in i :
        for k in j:
            lis1.append(k)
    print(len(i))
    lis.append(lis1)

0
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21

In [12]:
# df1=pd.DataFrame(lis)
# df2=pd.DataFrame(lis)
# df3=pd.DataFrame(lis)
# df4=pd.DataFrame(lis)
# df5=pd.DataFrame(lis)
# df8=pd.DataFrame(lis[1:])
df9=pd.DataFrame(lis[1:])

In [13]:
# df1
# df2
# df3
# df4
df9

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,203,651,155,565,141,455,191,383,254,364,...,294,451,304,514,337,398,359,335,375,275
1,178,664,122,576,102,466,147,394,212,368,...,263,448,274,513,305,397,325,333,338,273
2,167,665,105,582,78,468,118,384,175,347,...,239,451,256,512,278,391,296,327,307,268
3,173,667,110,581,83,468,127,390,191,357,...,247,454,258,513,283,395,300,330,311,271
4,194,665,133,581,108,474,153,400,217,370,...,269,454,284,520,313,401,331,338,340,280
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,109,698,35,605,-13,498,-17,398,-3,355,...,175,398,197,468,241,330,266,247,275,172
245,106,709,63,621,14,514,18,417,48,366,...,146,427,141,502,191,364,219,285,230,219
246,146,693,55,622,-9,504,-19,389,11,329,...,194,419,233,481,277,347,297,264,304,189
247,233,650,145,564,111,446,146,358,207,321,...,292,381,332,433,376,308,402,242,415,182
248,296,613,217,520,202,417,240,348,303,323,...,354,358,399,403,444,291,470,230,485,175

In [14]:
labels=["up","down","left","right","bwd","fwd","land","flip"]

# Create a dictionary mapping each element to a unique number
element_dict = {element: index for index, element in enumerate(labels)}

# Display the dictionary
print(element_dict)

{'up': 0, 'down': 1, 'left': 2, 'right': 3, 'bwd': 4, 'fwd': 5, 'land': 6, 'flip': 7}

In [15]:
# df1["label"]=0
# df1.loc[:199,"label"]=2
# df1

In [16]:
df9["label"]=7
cols=list(range(42))
cols.append("label")
df9.columns=cols
df9

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,label
0,203,651,155,565,141,455,191,383,254,364,...,451,304,514,337,398,359,335,375,275,7
1,178,664,122,576,102,466,147,394,212,368,...,448,274,513,305,397,325,333,338,273,7
2,167,665,105,582,78,468,118,384,175,347,...,451,256,512,278,391,296,327,307,268,7
3,173,667,110,581,83,468,127,390,191,357,...,454,258,513,283,395,300,330,311,271,7
4,194,665,133,581,108,474,153,400,217,370,...,454,284,520,313,401,331,338,340,280,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,109,698,35,605,-13,498,-17,398,-3,355,...,398,197,468,241,330,266,247,275,172,7
245,106,709,63,621,14,514,18,417,48,366,...,427,141,502,191,364,219,285,230,219,7
246,146,693,55,622,-9,504,-19,389,11,329,...,419,233,481,277,347,297,264,304,189,7
247,233,650,145,564,111,446,146,358,207,321,...,381,332,433,376,308,402,242,415,182,7
248,296,613,217,520,202,417,240,348,303,323,...,358,399,403,444,291,470,230,485,175,7

In [17]:
# left : 2 :0 to 199
# right :3 :200 to 399
# up :0    :400 to 599
# down :1    :600 to 799
# fwd :5    
# bwd :4

# Open the file in write mode
with open("/Users/aryansood/aims/AIMS_DRONE2/flip.txt", 'w') as file:
    # Write the entire list as a single line in the file
    file.write(','.join(map(str, lis)))

print(f'List saved to: /Users/aryansood/aims/AIMS_DRONE2/flip')

List saved to: /Users/aryansood/aims/AIMS_DRONE2/flip

In [24]:
df_data= pd.read_csv("/Users/aryansood/aims/AIMS_DRONE2/newdata_final_with_updown.csv")
df_data
# Remove rows where the 'label' column has the value 7
df_filtered = df_data[df_data['label'] != 7]
df_filtered.columns=cols
df_filtered

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,label
0,111,532,154,439,226,349,262,276,261,210,...,505,271,541,360,553,323,557,281,549,2.0
1,118,536,157,448,227,355,263,282,262,216,...,514,275,549,365,560,328,565,286,557,2.0
2,120,541,158,452,228,358,267,285,266,219,...,520,277,555,368,565,332,571,289,563,2.0
3,123,544,158,454,225,359,265,285,266,216,...,521,280,557,371,564,333,571,290,565,2.0
4,116,543,154,453,223,358,262,283,262,215,...,522,276,557,367,567,329,573,286,566,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,312,169,412,195,534,259,630,274,713,253,...,330,281,295,305,429,295,383,291,322,1.0
1688,370,154,474,183,594,249,691,265,772,244,...,322,364,277,375,413,364,370,365,311,1.0
1689,420,145,527,176,642,242,738,259,820,237,...,323,429,263,430,401,419,366,421,310,1.0
1690,458,146,567,172,682,235,775,253,853,231,...,319,476,256,476,393,462,358,464,304,1.0
1691,502,140,613,168,731,234,826,249,903,228,...,323,537,250,530,394,513,361,517,308,1.0

In [25]:
# result_df = pd.concat([df1, df2 , df3 ,df4, df5,df6,df7,df8 ], ignore_index=True)
result_df = pd.concat([df_filtered,df9 ], ignore_index=True)
result_df

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,label
0,111,532,154,439,226,349,262,276,261,210,...,505,271,541,360,553,323,557,281,549,2.0
1,118,536,157,448,227,355,263,282,262,216,...,514,275,549,365,560,328,565,286,557,2.0
2,120,541,158,452,228,358,267,285,266,219,...,520,277,555,368,565,332,571,289,563,2.0
3,123,544,158,454,225,359,265,285,266,216,...,521,280,557,371,564,333,571,290,565,2.0
4,116,543,154,453,223,358,262,283,262,215,...,522,276,557,367,567,329,573,286,566,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1736,109,698,35,605,-13,498,-17,398,-3,355,...,398,197,468,241,330,266,247,275,172,7.0
1737,106,709,63,621,14,514,18,417,48,366,...,427,141,502,191,364,219,285,230,219,7.0
1738,146,693,55,622,-9,504,-19,389,11,329,...,419,233,481,277,347,297,264,304,189,7.0
1739,233,650,145,564,111,446,146,358,207,321,...,381,332,433,376,308,402,242,415,182,7.0
1740,296,613,217,520,202,417,240,348,303,323,...,358,399,403,444,291,470,230,485,175,7.0

In [26]:
result_df["label"].nunique()

8

In [27]:
result_df["label"]

0       2.0
1       2.0
2       2.0
3       2.0
4       2.0
       ...
1736    7.0
1737    7.0
1738    7.0
1739    7.0
1740    7.0
Name: label, Length: 1741, dtype: float64

In [28]:
csv_file_path="/Users/aryansood/aims/AIMS_DRONE2/newdata_final_with_updown_flip.csv"
result_df.to_csv(csv_file_path, index=False)