In [28]:
import mediapipe as mp
import cv2
import time
import pandas as pd

In [10]:
# Initialize MediaPipe Hands module
mp_hands = mp.solutions.hands
hands = mp_hands.Hands()

# Function to extract landmarks
def get_landmarks(image):
    landmark_list = []
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image_rgb)
    
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            for landmark in hand_landmarks.landmark:
                # Multiply x and y values by image width and height to get pixel values
                x = int(landmark.x * image.shape[1])
                y = int(landmark.y * image.shape[0])
                landmark_list.append((x, y))
    return landmark_list

In [17]:
landmarks = []
left = []
cap=cv2.VideoCapture(1)
# print(f"collecting images for {i}")
time.sleep(5)
j=0
while len(left)<200:
    print(f"image number : {j}")
    j+=1
    ret,frame =cap.read()
    cv2.imshow("frame",frame)
    if get_landmarks(frame):
        left.append(get_landmarks(frame))
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

image number : 0
image number : 1
image number : 2
image number : 3
image number : 4
image number : 5
image number : 6
image number : 7
image number : 8
image number : 9
image number : 10
image number : 11
image number : 12
image number : 13
image number : 14
image number : 15
image number : 16
image number : 17
image number : 18
image number : 19
image number : 20
image number : 21
image number : 22
image number : 23
image number : 24
image number : 25
image number : 26
image number : 27
image number : 28
image number : 29
image number : 30
image number : 31
image number : 32
image number : 33
image number : 34
image number : 35
image number : 36
image number : 37
image number : 38
image number : 39
image number : 40
image number : 41
image number : 42
image number : 43
image number : 44
image number : 45
image number : 46
image number : 47
image number : 48
image number : 49
image number : 50
image number : 51
image number : 52
image number : 53
image number : 54
image number : 55
image number : 56
image number : 57
image number : 58
image number : 59
image number : 60
image number : 61
image number : 62
image number : 63
image number : 64
image number : 65
image number : 66
image number : 67
image number : 68
image number : 69
image number : 70
image number : 71
image number : 72
image number : 73
image number : 74
image number : 75
image number : 76
image number : 77
image number : 78
image number : 79
image number : 80
image number : 81
image number : 82
image number : 83
image number : 84
image number : 85
image number : 86
image number : 87
image number : 88
image number : 89
image number : 90
image number : 91
image number : 92
image number : 93
image number : 94
image number : 95
image number : 96
image number : 97
image number : 98
image number : 99
image number : 100
image number : 101
image number : 102
image number : 103
image number : 104
image number : 105
image number : 106
image number : 107
image number : 108
image number : 109
image number : 110
image number : 111
image number : 112
image number : 113
image number : 114
image number : 115
image number : 116
image number : 117
image number : 118
image number : 119
image number : 120
image number : 121
image number : 122
image number : 123
image number : 124
image number : 125
image number : 126
image number : 127
image number : 128
image number : 129
image number : 130
image number : 131
image number : 132
image number : 133
image number : 134
image number : 135
image number : 136
image number : 137
image number : 138
image number : 139
image number : 140
image number : 141
image number : 142
image number : 143
image number : 144
image number : 145
image number : 146
image number : 147
image number : 148
image number : 149
image number : 150
image number : 151
image number : 152
image number : 153
image number : 154
image number : 155
image number : 156
image number : 157
image number : 158
image number : 159
image number : 160
image number : 161
image number : 162
image number : 163
image number : 164
image number : 165
image number : 166
image number : 167
image number : 168
image number : 169
image number : 170
image number : 171
image number : 172
image number : 173
image number : 174
image number : 175
image number : 176
image number : 177
image number : 178
image number : 179
image number : 180
image number : 181
image number : 182
image number : 183
image number : 184
image number : 185
image number : 186
image number : 187
image number : 188
image number : 189
image number : 190
image number : 191
image number : 192
image number : 193
image number : 194
image number : 195
image number : 196
image number : 197
image number : 198
image number : 199

In [23]:
len(left)
# left

200

In [24]:
lis=[]
for i in left:
    lis1=[]
    for j in i :
        for k in j:
            lis1.append(k)
    lis.append(lis1)

In [29]:
df1=pd.DataFrame(lis)

In [30]:
df1

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,111,532,154,439,226,349,262,276,261,210,...,298,505,271,541,360,553,323,557,281,549
1,118,536,157,448,227,355,263,282,262,216,...,303,514,275,549,365,560,328,565,286,557
2,120,541,158,452,228,358,267,285,266,219,...,305,520,277,555,368,565,332,571,289,563
3,123,544,158,454,225,359,265,285,266,216,...,304,521,280,557,371,564,333,571,290,565
4,116,543,154,453,223,358,262,283,262,215,...,301,522,276,557,367,567,329,573,286,566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,733,584,757,474,821,393,878,338,906,293,...,909,563,975,609,963,624,933,624,906,619
196,746,609,771,497,834,413,890,350,925,302,...,922,586,992,639,984,647,950,647,920,644
197,777,576,795,465,848,385,898,330,924,295,...,942,540,1011,602,997,601,970,600,944,599
198,811,517,827,412,876,335,905,265,907,205,...,963,493,1036,545,1014,556,986,556,960,550
199,832,480,845,378,890,302,916,234,920,175,...,984,459,1051,506,1033,519,1006,519,983,514

In [31]:
labels=["up","down","left","right","bwd","fwd","land","flip"]

# Create a dictionary mapping each element to a unique number
element_dict = {element: index for index, element in enumerate(labels)}

# Display the dictionary
print(element_dict)

{'up': 0, 'down': 1, 'left': 2, 'right': 3, 'bwd': 4, 'fwd': 5, 'land': 6, 'flip': 7}

In [35]:
df1["label"]=0
df1.loc[:199,"label"]=2
df1

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,label
0,111,532,154,439,226,349,262,276,261,210,...,505,271,541,360,553,323,557,281,549,2
1,118,536,157,448,227,355,263,282,262,216,...,514,275,549,365,560,328,565,286,557,2
2,120,541,158,452,228,358,267,285,266,219,...,520,277,555,368,565,332,571,289,563,2
3,123,544,158,454,225,359,265,285,266,216,...,521,280,557,371,564,333,571,290,565,2
4,116,543,154,453,223,358,262,283,262,215,...,522,276,557,367,567,329,573,286,566,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,733,584,757,474,821,393,878,338,906,293,...,563,975,609,963,624,933,624,906,619,2
196,746,609,771,497,834,413,890,350,925,302,...,586,992,639,984,647,950,647,920,644,2
197,777,576,795,465,848,385,898,330,924,295,...,540,1011,602,997,601,970,600,944,599,2
198,811,517,827,412,876,335,905,265,907,205,...,493,1036,545,1014,556,986,556,960,550,2
199,832,480,845,378,890,302,916,234,920,175,...,459,1051,506,1033,519,1006,519,983,514,2

In [38]:
csv_file_path="/Users/aryansood/aims/AIMS_DRONE2/newdata.csv"
df1.to_csv(csv_file_path, index=False)

In [39]:
import csv

# Specify the file path where you want to save the CSV
csv_file_path = '/Users/aryansood/aims/AIMS_DRONE2/data_individual_line.csv'

with open(csv_file_path, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(lis)

print(f'List saved as CSV to: {csv_file_path}')

List saved as CSV to: /Users/aryansood/aims/AIMS_DRONE2/data_individual_line.csv

In [45]:
# left : 2 :0 to 199

# Open the file in write mode
with open("/Users/aryansood/aims/AIMS_DRONE2/left.txt", 'w') as file:
    # Write the entire list as a single line in the file
    file.write(','.join(map(str, lis)))

print(f'List saved to: /Users/aryansood/aims/AIMS_DRONE2/left')

List saved to: /Users/aryansood/aims/AIMS_DRONE2/left